package def

//RequestHeaders represents standard request headers.
var RequestHeaders = map[string]interface{}{
	"A-IM":                           0,
	"Accept":                         1,
	"Accept-Charset":                 2,
	"Accept-Encoding":                3,
	"Accept-Language":                4,
	"Accept-Datetime":                5,
	"Access-Control-Request-Method":  6,
	"Access-Control-Request-Headers": 7,
	"Authorization":                  8,
	"Cache-Control":                  9,
	"Connection":                     10,
	"Content-Length":                 11,
	"Content-Type":                   12,
	"Cookie":                         13,
	"Date":                           14,
	"Expect":                         15,
	"Forwarded":                      16,
	"From":                           17,
	"Host":                           18,
	"If-Match":                       19,
	"If-Modified-Since":              20,
	"If-None-Match":                  21,
	"If-Range":                       22,
	"If-Unmodified-Since":            23,
	"Max-Forwards":                   24,
	"Origin":                         25,
	"Pragma":                         26,
	"Proxy-Authorization":            27,
	"Range":                          28,
	"Referer":                        29,
	"TE":                             30,
	"User-Agent":                     31,
	"Upgrade":                        32,
	"Via":                            33,
	"Warning":                        34,
}
